# KerogsPHP Framework Configuration
# https://github.com/KSInfinite/KerogsPHP-Framework
# Thanks for using it.

# SEO Configuration
seo:
  title: "SoftScan3"
  title_short: "SoftScan3"
  description: "v2 de SoftScan, SoftScan est un scanneur d'image, vidéo et gif pour un dossier spécifique. Il permet de gérer facilement une galerie d'images sans configuration nécessaire. "
  keywords: "Galerie, Image, Scan, Video, GIF, Dossier, Clef usb, disque dur, image"
  author: "Kerogs"
  lang: "Français"
  lang_short: "fr"
  color: "#a038ec"
  image: ""
  favicon: "src/img/logo_c.png"
  sitemap: "src/xml/sitemap.xml"

# Labs/test IP authorization Configuration
labs:
  enable: false
  labsIPAuth:
    - 127.0.0.1

# Other
other:
  website_version: 3.1

framework:
  framework_version: 2.2.1-beta
  title: "KerogsPHP Framework"
  title_short: "KsPHP Framework"
